{{- if .Values.master_create_storage_class }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.master_storage_class_value }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
  {{- if eq .Values.master_storage_provisioner "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
{{- else if eq .Values.master_storage_provisioner "azure" }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: {{ .Values.data_storage_azure_type }}
  kind: {{ .Values.data_storage_azure_kind }}
{{- else if eq .Values.master_storage_provisioner "vmware" }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- else if eq .Values.master_storage_provisioner "bare" }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- else }}
# do nothing
{{- end }}
{{- end }}
