kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.name}}
  labels:
    app: {{ template "name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - endpoints
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.name}}
  labels:
    app: {{ template "name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
subjects:
- kind: ServiceAccount
  name: {{.Values.name}}
  namespace: {{.Release.Namespace}}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{.Values.name}}
  apiGroup: ""
